### ISSUE TITLE
No PHP for you!

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-SimplePages#12]
With tinymce turned off, angle brackets are still converted to entities, so <?php ?> can't work. Possible that this is an artifact from the security setting of filtering HTML being on, but can't check because currently can't change those settings (see Omeka issue https://github.com/omeka/Omeka/issues/386 )

Either way, I suspect people will still want their PHP SimplePages, so we'll need to figure out a way to have that happen.

**Comment by iwemuiser** [comment]
Some time ago I updated Omeka to 2.2.2 and also the SimplePages plugin to 3.0.4. I disabled the configuration setting (not the global one) but there is still no php functionality. Am I missing something? Are there other settings that work on php functionality in SimplePages?
