### ISSUE TITLE
Test tinymce4

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-SimplePages#32]
(see omeka/omeka#837)

Branch "tinymce4", core branch "tinymce4"

Editors appear on add/edit. Of note: the configuration of the editor is now the same as all other editors in the admin (previously Simple Pages had its own custom config). Pretty much the only interesting unique interaction here is the "use editor" checkbox.

**Comment by mebrett** [comment]
When you toggle editor off, the markup remains in the text editing area. If this is expected behavior, then it's fine. 
<img width="704" alt="screen shot 2018-01-26 at 12 03 08 pm" src="https://user-images.githubusercontent.com/2314070/35451347-e678c64e-0290-11e8-8db4-f70cf47b14c6.png">

**Comment by zerocrates** [comment]
I don't believe that's different than before.
